name: CI Angular app through Github Actions
on: push
jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Use Node.js 14.x
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: 14.x
  #     - name: Setup
  #       run: npm i
  #     - name: Test
  #       run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI

  build:
    runs-on: ubuntu-latest
    # needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Setup
        run: npm i
      - name: Build
        run: npm run build
      - name: check
        run: ls -la
      - name: Build the Docker image
        run: docker build . --file github.Dockerfile
      # - name: Login to DockerHub
      #   uses: docker/login-action@v1 
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v2
      #   with:
      #     registry: ghcr.io
      #     push: true
      #     tags: b1ackadder/angular-starter:latest
      # - name: Archive build
      #   if: success()
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: dist
      #     path: dist 

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v1
  #     - name: Download build
  #       uses: actions/download-artifact@v1
  #       with:
  #         name: dist
  #     - name: Login to DockerHub
  #       uses: docker/login-action@v1 
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}
  #     - name: Build and push Docker image
  #       uses: docker/build-push-action@v2
  #       with:
  #         push: true
  #         tags: b1ackadder/angular-starter:latest
          
        